In [150]:
#import dependencies
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from collections import Counter
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
import pickle

In [172]:
#read in file 
data = Path('../results/DataProcessingExtractFile-RawData.csv')
df = pd.read_csv(data)
#confirm
df.head(10)

,Diabetes_Status,HighBP,HighChol,CholCheck,BMI_Range,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,Mental_Health_Range,Physical_Health_Range,DiffWalk,Sex,Age,Education,Income
0,1,1.0,1.0,1.0,4,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,4,3,1.0,0.0,9.0,4.0,3.0
1,1,0.0,0.0,0.0,3,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,1,1,0.0,0.0,7.0,6.0,1.0
2,1,1.0,1.0,1.0,3,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,6,6,1.0,0.0,9.0,4.0,8.0
3,1,1.0,0.0,1.0,3,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,0.0,11.0,3.0,6.0
4,1,1.0,1.0,1.0,2,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,0.0,11.0,5.0,4.0
5,1,1.0,1.0,1.0,3,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,1.0,10.0,6.0,8.0
6,1,1.0,0.0,1.0,4,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,1,3,0.0,0.0,9.0,6.0,7.0
7,1,1.0,1.0,1.0,3,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,1,1,1.0,0.0,11.0,4.0,4.0
8,2,1.0,1.0,1.0,4,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,6,6,1.0,0.0,9.0,5.0,1.0
9,1,0.0,0.0,1.0,2,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,2.0,1,1,0.0,1.0,8.0,4.0,3.0

In [173]:
# Linear Regression Model (Change and add the Random Decision Tree model) 

y = df["Diabetes_Status"]
X = df.drop(columns="Diabetes_Status")

In [176]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y,
                                                    test_size=0.25)
X_train.shape

(190260, 21)

In [177]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=200,
   random_state=1)

In [178]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [179]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(5)

   Prediction  Actual
0           1       1
1           1       1
2           1       1
3           1       1
4           1       1

In [180]:
#read in file from survey website
final_predict = Path('../site-dashboard/export/surveyExport.json')
prediction_df = pd.read_json(final_predict, orient='index')
prediction_df

,Sex,HighBP,CholCheck,HighChol,PhysActivity,HvyAlcoholConsumP,AnyHealthcare,Education,GenHlth,Income,...,Fruits,Veggies,NoDocbcCost,Mental_Health_Range,Physical_Health_Range,BMI_Range,Smoker,Stroke,HeartDiseaseorAttack,DiffWalk
row 1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [167]:
#reset index 
prediction_df.reset_index(inplace=True)

In [168]:
#drop index
prediction_df.drop(columns=['index'])

,Sex,HighBP,CholCheck,HighChol,PhysActivity,HvyAlcoholConsumP,AnyHealthcare,Education,GenHlth,Income,...,Fruits,Veggies,NoDocbcCost,Mental_Health_Range,Physical_Health_Range,BMI_Range,Smoker,Stroke,HeartDiseaseorAttack,DiffWalk
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [169]:
#validate
predict_df = prediction_df[['HighBP', "HighChol", "CholCheck", "BMI_Range", "Smoker", "Stroke", "HeartDiseaseorAttack", "PhysActivity", "Fruits", "Veggies", "HvyAlcoholConsumP", "AnyHealthcare", "NoDocbcCost", "GenHlth", "Mental_Health_Range", "Physical_Health_Range", "DiffWalk", "Sex", "Age", "Education", "Income"]]
predict_df.head()

,HighBP,HighChol,CholCheck,BMI_Range,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,Mental_Health_Range,Physical_Health_Range,DiffWalk,Sex,Age,Education,Income
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [181]:
#set  predict dataframe to predict values  and run prediction against trained model 
y_pred = classifier.predict(predict_df)
#validate result completes 
y_pred

C:\Users\kbrabec\Anaconda3\envs\mlenv\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- HvyAlcoholConsumP
Feature names seen at fit time, yet now missing:
- HvyAlcoholConsump

  warnings.warn(message, FutureWarning)

array([1], dtype=int64)

In [182]:
#set value to send back to website 
prediction = y_pred